[project]
name = "master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bpython>=0.25",
    "faiss-gpu>=1.7.2",
    "sentence-transformers>=3.4.1",
    "tiktoken>=0.8.0",
    "umap-learn>=0.5.7",
]
